BikeSharing/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('registrasi/', include('registrasi.urls')),
    path('', include('landingPage.urls')),
    path('penugasan', include('penugasan.urls')),
    path('acara', include('acara.urls')),
    path('stasiun', include('stasiun.urls')),
    path('sepeda', include('sepeda.urls')),
    path('peminjaman', include('peminjaman.urls')),
    path('voucher', include('voucher.urls')),
    path('transaksi/', include('transaksi.urls')),
    path('laporan/', include('laporan.urls')),
]

acara/urls.py
from django.urls import path
from acara import views
app_name = 'acara'

urlpatterns = [
	path('', views.acara, name = 'acara'),
	path('/add_acara', views.add_acara, name = 'add_acara'),
	path('/post_acara', views.post_acara, name = 'post_acara'),
	path('delete_acara/', views.delete_acara, name='delete_acara'),
    path('update_acara/', views.update_acara, name='update_acara'),
    path('detail_update_acara/', views.detail_update_acara, name='detail_update_acara'),
	path('/sortAcaraDESC/',views.sortAcaraDESC, name = 'sortAcaraDESC'),
	path('/sortAcaraASC/', views.sortAcaraASC, name = 'sortAcaraASC'),
]

sepeda/urls.py
from django.urls import path
from sepeda import views
app_name = 'sepeda'

urlpatterns = [
	path('', views.listsepeda, name = 'sepeda'),
	path('/createsepeda',views.sepeda,name='createsepeda'),
	path('/updatesepeda',views.updatesepeda,name='updatesepeda'),
	path('/postsepeda',views.postsepeda, name = 'postsepeda'),
    path('/deletesepeda',views.deletesepeda, name = 'deletesepeda'),
    path('/detailupdate',views.detailupdate, name = 'detailupdate'),
]

stasiun/urls.py
from django.urls import path
from stasiun import views
app_name = 'stasiun'

urlpatterns = [
	path('', views.liststasiun, name = 'stasiun'),
	path('/createstasiun',views.stasiun,name='createstasiun'),
	path('/updatestasiun/',views.updatestasiun,name='updatestasiun'),
	path('/poststasiun',views.poststasiun, name = 'poststasiun'),
    path('/deletestasiun',views.deletestasiun, name = 'deletestasiun'),
    path('/detailupdate',views.detailupdate, name = 'detailupdate'),
]

stasiun/models.py
from django.db import models

stasiun/forms.py
# from django import forms
# from .models import *
#
# FILTER_CHOICES = []
# SORTING_CHOICES = []
#
# filter_data = list(Stasiun.objects.raw("SELECT DISTINCT id_stasiun, alamat FROM stasiun"))
# sorting_data = list(Stasiun.objects.raw("SELECT DISTINCT id_stasiun, nama kategori FROM stasiun"))
#
# for i in range(len(filter_data)):
#     if (filter_data[i].filter, filter_data[i].filter) not in FILTER_CHOICES:
#         FILTER_CHOICES.append((filter_data[i].filter, filter_data[i].filter))
# for i in range(len(sorting_data)):
#     if (sorting_data[i].sorting, sorting_data[i].sorting) not in SORTING_CHOICES:
#         SORTING_CHOICES.append((sorting_data[i].kategori, kategori_data[i].kategori))
#
# class FilterChoice(forms.Form):
#     filter = forms.ChoiceField(
#         choices=FILTER_CHOICES,
#         required=True,
#         widget=forms.Select(
#             attrs={
#                 'data-toggle': 'dropdown',
#                 'aria-expanded': 'false',
#                 'type': 'button',
#             }
#         ),
#     )
#
# class SortingChoice(forms.Form):
#     sorting = forms.ChoiceField(
#         choices=SORTING_CHOICES,
#         required=True,
#         widget=forms.Select(
#             attrs={
#                 'class':'form-control',
#             }
#         ),
#     )

stasiun/views.py
from django.shortcuts import render
from django.db import connection
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
# from .forms import FilterChoice, SortingChoice

response = {}

def liststasiun(request):
	response={}
	c = connection.cursor()
	c.execute('set search_path to bike_sharing,public')
	c.execute("select * from stasiun")
	result1 = c.fetchall()
	response['stasiun'] = result1
	#print(response)
	return render(request, 'daftar_stasiun.html',response)

def stasiun(request):
	response={}
	c = connection.cursor()
	c.execute('set search_path to bike_sharing,public')
	c.execute("select nama from stasiun")

	result1 = c.fetchall()
	response['stasiun'] = result1
	print(response)
	return render(request, 'createStasiun.html',response)

def poststasiun(request):
	if(request.method=="POST"):
		nama = request.POST['nama']
		alamat = request.POST['alamat']
		longitude = request.POST['longitude']
		latitude = request.POST['latitude']

		c = connection.cursor()
		c.execute('set search_path to bike_sharing,public')
		c.execute("SELECT id_stasiun FROM stasiun")
		id_stasiun = c.fetchall()
		for row in id_stasiun:
			id_stasiun = row[0]

		c.execute("SELECT id_stasiun FROM stasiun ORDER BY cast (id_stasiun as int) DESC;")
		result = c.fetchone()
		id_stasiun = int(result[0]) +1

		print(id_stasiun)
		c.execute("INSERT INTO stasiun(id_stasiun,alamat,lati,longi,nama) VALUES ("+"'"+str(id_stasiun)+"','" +str(alamat)+"'," + str(latitude) +",'" + str(longitude) +"','" + str(nama)+"');")
		return HttpResponseRedirect('/stasiun')

	else:
		messages.error(request, "failed")
		return HttpResponseRedirect('/stasiun/createstasiun')

def updatestasiun(request):
	if(request.method=="POST"):
		print("hehe")
		nama = request.POST['nama']
		alamat = request.POST['alamat']
		longitude = request.POST['longitude']
		latitude = request.POST['latitude']
		id_stasiun= request.POST['id_stasiun']

		c = connection.cursor()
		c.execute('set search_path to bike_sharing,public')
		c.execute("update stasiun set nama='"+nama+"', alamat='"+alamat+"', lat='"+latitude+"', long='"+longitude+"' where id_stasiun = '"+id_stasiun+"';")

		messages.error(request, "success")
		return HttpResponseRedirect('/stasiun')

	else:
		messages.error(request, "failed")
		return HttpResponseRedirect('/stasiun')


@csrf_exempt
def deletestasiun(request):
	if(request.method=="POST"):
		id_stasiun= request.POST['id']
		c = connection.cursor()
		c.execute('set search_path to bike_sharing,public')
		c.execute("DELETE FROM stasiun WHERE id_stasiun='"+id_stasiun+"';")

		return HttpResponseRedirect('/stasiun')

	else:
		messages.error(request, "failed")
		return HttpResponseRedirect('/stasiun')

@csrf_exempt
def detailupdate(request):
    if(request.method=="POST"):
        response={}
        stasiun= request.POST['id']
        c = connection.cursor()
        c.execute('set search_path to bike_sharing,public')
        c.execute("SELECT * FROM stasiun WHERE id_stasiun='"+stasiun+"';")
        stasiun = c.fetchone()
        response['stasiun'] = stasiun

        return JsonResponse(response)

    else:
        messages.error(request, "failed")
        return HttpResponseRedirect('/stasiun')

stasiun/templates/createStasiun.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load static %}

{% block title %}
{% endblock title %}

{% block head %}
    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static 'material-design-iconic-font.css' %}">
    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- JS -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="js/main.js"></script>
{% endblock %}

{% block body %}

<!-- Add stasiun form -->
<section class="add">
  <div class="container-edit">
      <div class="add-content">
        <div class="row">
          <div class="col-md-6">
            <div class="add-form">
                <h2 class="form-title1">Penambahan stasiun</h2>
                <form action="/stasiun/poststasiun" method="POST">
                  {% csrf_token %}
                  <div class="form-group">
                      <label for="name"><i class="name"></i></label>
                      <input type="text" name="nama" id="name" placeholder="Nama" required />
                  </div>
                  <div class="form-group">
                      <label for="alamat"><i class="name"></i></label>
                      <input type="text" name="alamat" id="name" placeholder="Alamat" required />
                  </div>
                  <div class="form-group">
                      <label for="longitude"><i class="name"></i></label>
                      <input type="text" name="latitude" id="name" placeholder="Latitude" />
                  </div>
                  <div class="form-group">
                      <label for="latitude"><i class="name"></i></label>
                      <input type="text" name="longitude" id="name" placeholder="Longitude" />
                  </div>
                  <div class="form-group form-button">
                      <input type="submit" name="add" id="add" class="form-submit" value="Submit"/>
                  </div>
                </form>
            </div>
          </div>
          <div class="col-md-6">
            <div class="add-image">
                <figure><img src="https://scontent.fcgk18-2.fna.fbcdn.net/v/t1.0-9/59487760_1566002416865635_6596520650792239104_n.jpg?_nc_cat=104&_nc_ht=scontent.fcgk18-2.fna&oh=14ff139985fcd569ad583af921d082c2&oe=5D5F5346"></figure>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>
{% endblock %}

stasiun/templates/daftar_stasiun.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load static %}

{% block title %}
{% endblock title %}

{% block head %}

  <link rel="stylesheet" href="{% static 'css/style1.css' %}">
  <link rel="stylesheet" href="{% static 'material-design-iconic-font.css' %}">

<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>

<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
<script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
{% endblock %}

{% block body %}

<!-- Add stasiun list -->
<!-- <div class="cd-popup" role="alert">
    <div class="cd-popup-container">
          <p>Are you sure you want to delete this element?</p>
          <ul class="cd-buttons">
              <li onclick="yesFunction()"><a href="#0">Yes</a></li>
              <li onclick="cancelFunction()"><a href="#0">No</a></li>
          </ul>
    </div> <!-- cd-popup-container -->
<!-- </div> --> 
<div class="container-daftar">
    <div class="add-content">
    	<div class="row">
            <h2 class="form-title1">Daftar Stasiun</h2>
              </div>
              {% if request.session.role == "petugas" %}
              <div class="table-responsive">


              <table id="mytable" class="table table-bordred table-striped">

                 <thead>
                    <th>Nomor</th>
                    <th>Nama stasiun</th>
                    <th>Alamat</th>
                    <th>Latitude</th>
                    <th>Longitude</th>
                    <th>Action</th>
                 </thead>
                <tbody>
                {% for i in stasiun %}
                      <tr>
                      <td>{{i.0}}</td>
                      <td>{{i.4}}</td>
                      <td>{{i.1}}</td>
                      <td>{{i.2}}</td>
                      <td>{{i.3}}</td>

                      <td><a data-placement="top" data-toggle="tooltip" href="{% url 'stasiun:updatestasiun' %}" title="Update"><button class="btn btn-primary btn-xs" id="{{i.0}}" data-toggle="modal" onclick="updateModal(this.id)" data-target="#exampleModalCenter">Update</button></a>
                          <a data-placement="top" data-toggle="tooltip" title="Delete"><a href="{% url 'sepeda:deletesepeda' %}" class="btn btn-danger btn-xs" data-title="Edit" data-toggle="modal" data-target="#edit"  onclick="return confirm('Are you sure you want to delete this item?');">Delete</a></td>
                      </tr>
                  {% endfor %}
                  </tbody>
              </table>
              {% elif request.session.role == "anggota" %}
              <div class="table-responsive">
              <table id="mytable" class="table table-bordred table-striped">

                 <thead>
                    <th>Nomor</th>
                    <th>Nama stasiun</th>
                    <th>Alamat</th>
                    <th>Latitude</th>
                    <th>Longitude</th>
                 </thead>
                <tbody>
                {% for i in stasiun %}
                      <tr>
                        <td>{{i.0}}</td>
                        <td>{{i.4}}</td>
                        <td>{{i.1}}</td>
                        <td>{{i.2}}</td>
                        <td>{{i.3}}</td>
                      </tr>
                {% endfor %}
                </tbody>
              </table>
              {% endif %}
            </div>
    	</div>
  </div>
  <!-- Modal -->
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalCenterTitle">Update Stasiun</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                <div class="spinner-border false"role="status">
                    <span class="sr-only">Loading...</span>
                </div>

                <form id="load" class="true">
                  {% csrf_token %}
                    <div class="form-group">
                      <label for="formGroup">Nama</label>
                      <input type="text" class="form-control" id="namaStasiun" placeholder="Nama">
                    </div>
                    <div class="form-group">
                      <label for="formGroup2">Alamat</label>
                      <input type="text" class="form-control" id="alamatStasiun" placeholder="Alamat">
                    </div>
                    <div class="form-group">
                        <label for="formGroup2">Latitude</label>
                        <input type="text" class="form-control" id="latitudeStasiun" placeholdeR="Latitude">
                      </div>
                      <div class="form-group">
                          <label for="formGroup2">Longitude</label>
                          <input name="longitude" type="text" class="form-control" id="longitudeStasiun" placeholder="Longitude">
                      </div>
                </form>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
              <button type="button" class="btn btn-primary" onclick="updateStasiun()">Save changes</button>
            </div>
          </div>
        </div>
      </div>

</div>

<script src="{% static '/js/main.js' %}"></script>
{% endblock %}

stasiun/templates/updateStasiun.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load static %}

{% block title %}
{% endblock title %}

{% block head %}
    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static 'material-design-iconic-font.css' %}">
    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- JS -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="js/main.js"></script>
{% endblock %}

{% block body %}

<section class="update">
    <div class="container-edit">
        <div class="update-content">
          <div class="row">
            <div class="col-md-6">
              <div class="update-image">
                  <figure><img src="https://scontent.fcgk18-1.fna.fbcdn.net/v/t1.0-9/59710129_1566002423532301_945452520963047424_n.jpg?_nc_cat=105&_nc_ht=scontent.fcgk18-1.fna&oh=fc4b9a06ffeb557441c11e096a563595&oe=5D7028CF"></figure>
              </div>
            </div>
            <div class="col-md-6">
              <div class="update-form">
                  <h2 class="form-title">Update stasiun</h2>
                  <form action="/stasiun/poststasiun" method="POST">
                  {% csrf_token %}
                    <div class="form-group">
                        <label for="nama"><i class="name"></i></label>
                        <input type="text" name="nama" id="name" placeholder="Nama" required />
                    </div>
                    <div class="form-group">
                        <label for="alamat"><i class="name"></i></label>
                        <input type="text" name="alamat" id="name" placeholder="Alamat" required />
                    </div>
                    <div class="form-group">
                        <label for="latitude"><i class="name"></i></label>
                        <input type="text" name="latitude" id="name" placeholder="Latitude" />
                    </div>
                    <div class="form-group">
                        <label for="longitude"><i class="name"></i></label>
                        <input type="text" name="longitude" id="name" placeholder="Longitude" />
                    </div>
                    <div class="form-group form-button">
                        <input type="submit" name="update" id="update" class="form-submit" value="Update"/>
                    </div>
                  </form>
              </div>
            </div>
          </div>
        </div>
    </div>
</section>
{% endblock %}