BikeSharing/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('registrasi/', include('registrasi.urls')),
    path('', include('landingPage.urls')),
    path('penugasan', include('penugasan.urls')),
    path('acara', include('acara.urls')),
    path('stasiun', include('stasiun.urls')),
    path('sepeda', include('sepeda.urls')),
    path('peminjaman', include('peminjaman.urls')),
    path('voucher', include('voucher.urls')),
    path('transaksi/', include('transaksi.urls')),
    path('laporan/', include('laporan.urls')),
]

acara/urls.py
from django.urls import path
from acara import views
app_name = 'acara'

urlpatterns = [
	path('', views.acara, name = 'acara'),
	path('/add_acara', views.add_acara, name = 'add_acara'),
	path('/post_acara', views.post_acara, name = 'post_acara'),
	path('delete_acara/', views.delete_acara, name='delete_acara'),
    path('update_acara/', views.update_acara, name='update_acara'),
    path('detail_update_acara/', views.detail_update_acara, name='detail_update_acara'),
	path('/sortAcaraDESC/',views.sortAcaraDESC, name = 'sortAcaraDESC'),
	path('/sortAcaraASC/', views.sortAcaraASC, name = 'sortAcaraASC'),
]

penugasan/urls.py
from django.urls import path
from penugasan import views
app_name = 'penugasan'


urlpatterns = [
	path('', views.penugasan, name = 'penugasan'),
	path('/add_penugasan', views.add_penugasan, name = 'add_penugasan'),
	path('/post_penugasan', views.post_penugasan, name = 'post_penugasan'),

	path('/sortPetugasDESC/',views.sortPetugasDESC, name = 'sortPetugasDESC'),
	path('/sortPetugasASC/', views.sortPetugasASC, name = 'sortPetugasASC'),
]

sepeda/urls.py
from django.urls import path
from sepeda import views
app_name = 'sepeda'

urlpatterns = [
	path('', views.listsepeda, name = 'sepeda'),
	path('/createsepeda',views.sepeda,name='createsepeda'),
	path('/updatesepeda',views.updatesepeda,name='updatesepeda'),
	path('/postsepeda',views.postsepeda, name = 'postsepeda'),
    path('/deletesepeda',views.deletesepeda, name = 'deletesepeda'),
    path('/detailupdate',views.detailupdate, name = 'detailupdate'),
]

stasiun/urls.py
from django.urls import path
from stasiun import views
app_name = 'stasiun'

urlpatterns = [
	path('', views.liststasiun, name = 'stasiun'),
	path('/createstasiun',views.stasiun,name='createstasiun'),
	path('/updatestasiun/',views.updatestasiun,name='updatestasiun'),
	path('/poststasiun',views.poststasiun, name = 'poststasiun'),
    path('/deletestasiun',views.deletestasiun, name = 'deletestasiun'),
    path('/detailupdate',views.detailupdate, name = 'detailupdate'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">

        {% block title %}
            <title>Bike Sharing</title>
        {% endblock %}

        <!-- Bootstrap core CSS -->
        <link href="{% static "vendor/landingPage/bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">

        <!-- Custom fonts for this template -->
        <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">

        <!-- Custom styles for this template -->
        <link href="{% static "css/landingPage/one-page-wonder.min.css" %}" rel="stylesheet">
        {% block head %}
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        {% endblock %}

        <style>
            .dropdown-content {
                display: none;
                position: absolute;
                background-color: #f9f9f9;
                min-width: 160px;
                box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
                z-index: 1;
            }
                .dropdown-content a {
                float: none;
                color: black;
                padding: 12px 16px;
                text-decoration: none;
                display: block;
                text-align: left;
            }

                .dropdown-content a:hover {
                background-color: #ddd;
            }
                .dropdown:hover .dropdown-content {
                display: block;
            }
        </style>

    </head>

    <body id="page-top">
        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
            <div class="container">
                <a class="navbar-brand" href="{% url 'landingPage' %}">BikeSharing</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">

                    {% if request.session.role == "anggota" %}
                        <li class="nav-item">
                            <div class="dropdown">
                                <a class="nav-link" href="#">Stasiun</a>
                                <div class="dropdown-content">
                                    <a href="{% url "stasiun:createstasiun" %}">Create</a>
                                    <a href="{% url "stasiun:stasiun" %}">Lists</a>
                                </div>
                            </div>
                        </li>
                        <li class="nav-item">
                            <div class="dropdown">
                                <a class="nav-link" href="#">Sepeda</a>
                                <div class="dropdown-content">
                                    <a href="{% url "sepeda:createsepeda" %}">Create</a>
                                    <a href="{% url "sepeda:sepeda" %}">Lists</a>
                                </div>
                            </div>
                        </li>
                        <li class="nav-item">
                            <div class="dropdown">
                                <a class="nav-link" href="#">Peminjaman</a>
                                <div class="dropdown-content">
                                    <a href="{% url "peminjaman" %}">Create</a>
                                    <a href="{% url "daftar_peminjaman" %}">Lists</a>
                                </div>
                            </div>
                        </li>
                        <li class="nav-item">
                            <div class="dropdown">
                                <a class="nav-link">Transaksi</a>
                                <div class="dropdown-content">
                                    <a href="{% url "riwayat" %}">Riwayat</a>
                                    <a href="{% url "topup" %}">Top Up</a>
                                </div>
                            </div>
                        </li>
                        <li class="nav-item">
                            <div class="dropdown">
                                <a class="nav-link" href="#">Acara</a>
                                <div class="dropdown-content">
                                    <a href="{% url "acara:add_acara" %}">Create</a>
                                    <a href="{% url "acara:acara" %}">Lists</a>
                                </div>
                            </div>
                        </li>
                        <li class="nav-item">
                            <div class="dropdown">
                                <a class="nav-link" href="#">Voucher</a>
                                <div class="dropdown-content">
                                    <a href="{% url "voucher" %}">Create</a>
                                    <a href="{% url "daftar_voucher" %}">Lists</a>
                                </div>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url "logout" %}">Log Out</a>
                        </li>

                    {% elif request.session.role == "petugas" %}
                        <li class="nav-item">
                            <div class="dropdown">
                                <a class="nav-link" href="#">Penugasan</a>
                                <div class="dropdown-content">
                                        <a href="{% url "penugasan:add_penugasan" %}">Create</a>
                                        <a href="{% url "penugasan:penugasan" %}">Lists</a>
                                </div>
                            </div>
                        </li>
                        <li class="nav-item">
                            <div class="dropdown">
                                <a class="nav-link" href="#">Stasiun</a>
                                <div class="dropdown-content">
                                    <a href="{% url "stasiun:createstasiun" %}">Create</a>
                                    <a href="{% url "stasiun:stasiun" %}">Lists</a>
                                </div>
                            </div>
                        </li>
                        <li class="nav-item">
                            <div class="dropdown">
                                <a class="nav-link" href="#">Sepeda</a>
                                <div class="dropdown-content">
                                    <a href="{% url "sepeda:createsepeda" %}">Create</a>
                                    <a href="{% url "sepeda:sepeda" %}">Lists</a>
                                </div>
                            </div>
                        </li>
                        <li class="nav-item">
                            <div class="dropdown">
                                <a class="nav-link" href="#">Acara</a>
                                <div class="dropdown-content">
                                    <a href="{% url "acara:add_acara" %}">Create</a>
                                    <a href="{% url "acara:acara" %}">Lists</a>
                                </div>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url "daftarLaporan" %}">Daftar Laporan</a>
                        </li>
                        <li class="nav-item">
                            <div class="dropdown">
                                <a class="nav-link" href="#">Peminjaman</a>
                                <div class="dropdown-content">
                                    <a href="{% url "peminjaman" %}">Create</a>
                                    <a href="{% url "daftar_peminjaman" %}">Lists</a>
                                </div>
                            </div>
                        </li>
                        <li class="nav-item">
                            <div class="dropdown">
                                <a class="nav-link" href="#">Voucher</a>
                                <div class="dropdown-content">
                                    <a href="{% url "voucher" %}">Create</a>
                                    <a href="{% url "daftar_voucher" %}">Lists</a>
                                </div>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url "logout" %}">Log Out</a>
                        </li>

                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url "registrasi" %}">Log In</a>
                        </li>

                    {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        {% block body %}
        {% endblock %}
    </body>
</html>