BikeSharing/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('registrasi/', include('registrasi.urls')),
    path('', include('landingPage.urls')),
    path('penugasan', include('penugasan.urls')),
    path('acara', include('acara.urls')),
    path('stasiun', include('stasiun.urls')),
    path('sepeda', include('sepeda.urls')),
    path('peminjaman', include('peminjaman.urls')),
    path('voucher', include('voucher.urls')),
    path('transaksi/', include('transaksi.urls')),
    path('laporan/', include('laporan.urls')),
]

acara/urls.py
from django.urls import path
from acara import views
app_name = 'acara'

urlpatterns = [
	path('', views.acara, name = 'acara'),
	path('/add_acara', views.add_acara, name = 'add_acara'),
	path('/post_acara', views.post_acara, name = 'post_acara'),
	path('delete_acara/', views.delete_acara, name='delete_acara'),
    path('update_acara/', views.update_acara, name='update_acara'),
    path('detail_update_acara/', views.detail_update_acara, name='detail_update_acara'),
	path('/sortAcaraDESC/',views.sortAcaraDESC, name = 'sortAcaraDESC'),
	path('/sortAcaraASC/', views.sortAcaraASC, name = 'sortAcaraASC'),
]

sepeda/urls.py
from django.urls import path
from sepeda import views
app_name = 'sepeda'

urlpatterns = [
	path('', views.listsepeda, name = 'sepeda'),
	path('/createsepeda',views.sepeda,name='createsepeda'),
	path('/updatesepeda',views.updatesepeda,name='updatesepeda'),
	path('/postsepeda',views.postsepeda, name = 'postsepeda'),
    path('/deletesepeda',views.deletesepeda, name = 'deletesepeda'),
    path('/detailupdate',views.detailupdate, name = 'detailupdate'),
]

sepeda/models.py
from django.db import models

# Create your models here.
class Stasiun(models.Model):
    nama = models.CharField(primary_key=True, max_length=50)
    alamat = models.CharField(max_length=300)
    latitude = models.IntegerField(blank=True, null=True)
    longitude = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'stasiun'

sepeda/forms.py
from django import forms
from .models import Stasiun


class StasiunForm(forms.Form):
    nama = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class': 'form-field flex-column'}))
    alamat = forms.CharField(max_length=300, widget=forms.TextInput(attrs={'class': 'form-field flex-column'}))
    latitude = forms.CharField(widget=forms.NumberInput(attrs={'class': 'form-field flex-column'}), required=False)
    longitude = forms.CharField(widget=forms.NumberInput(attrs={'class': 'form-field flex-column'}), required=False)

sepeda/views.py
from django.shortcuts import render
from django.db import connection
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
# from .forms import FilterChoice, SortingChoice

# Create your views here.
def sepeda(request):
    response={}
    c = connection.cursor()
    c.execute('set search_path to bike_sharing,public')
    c.execute("SELECT nama FROM stasiun")

    result1 = c.fetchall()
    response['stasiun'] = result1
    print(response)
    return render(request, 'createsepeda.html',response)

def postsepeda(request):
    if(request.method=="POST"):
        merk = request.POST['merk']
        jenis = request.POST['jenis']
        status = request.POST['status']
        stasiun = request.POST['stasiun']
        penyumbang = request.POST['penyumbang']

        print(status)
        statusNow = False
        if(str(status)=='Tersedia'):
            statusNow = True
        else:
            statusNow = False

        c = connection.cursor()
        c.execute('set search_path to bike_sharing,public')
        c.execute("select a.no_kartu from anggota as a, person as p where p.nama='"+penyumbang+"' and p.ktp = a.ktp;")
        result = c.fetchone()
        no_kartu_penyumbang = result[0]

        c.execute("select id_stasiun from stasiun where nama='"+stasiun+"';")
        result1 = c.fetchone()
        id_stasiun = result1[0]

        c.execute("select nomor from sepeda order by cast (nomor as int) desc;")
        result2 = c.fetchone()
        nomor = int(result2[0]) +1

        c.execute("INSERT INTO sepeda(nomor,merk,jenis,status,id_stasiun,no_kartu_penyumbang) values("+"'"+str(nomor)+"','" +str(merk)+"','" + str(jenis) +"','" + str(statusNow) +"', '" + str(id_stasiun) +"', '" + str(no_kartu_penyumbang) +"' );")

        return HttpResponseRedirect('/sepeda')

    else:
        messages.error(request, "failed")
        return HttpResponseRedirect('/sepeda/createsepeda')


def listsepeda(request):
    response={}
    c = connection.cursor()
    c.execute('set search_path to bike_sharing,public')
    c.execute("select s.nama, p.nama, n.nomor, n.merk, n.jenis, n.status from sepeda as n, stasiun as s, person as p, anggota as a where n.no_kartu_penyumbang = a.no_kartu and a.ktp = p.ktp and n.id_stasiun = s.id_stasiun; ")
    result1 = c.fetchall()
    response['sepeda'] = result1
    print(response)
    return render(request, 'daftar_sepeda.html',response)


def updatesepeda(request):
    if(request.method=="POST"):
        merk = request.POST['merk']
        jenis = request.POST['jenis']
        status = request.POST['status']
        stasiun = request.POST['stasiun']
        penyumbang = request.POST['penyumbang']
        nomor = request.POST['nomor']

        statusNow = False
        if(str(status)=='Tersedia'):
          statusNow = True
        else:
          statusNow = False

        c = connection.cursor()
        c.execute('set search_path to bike_sharing,public')

        c.execute("select a.no_kartu from anggota as a, person as p where p.nama='"+penyumbang+"' and p.ktp = a.ktp")
        result = c.fetchone()
        no_kartu = result[0]

        c.execute("update sepeda set merk='"+merk+"', jenis='"+jenis+"', status='"+str(statusNow)+"', no_kartu_penyumbang='"+no_kartu+"' where nomor = '"+str(nomor)+"';")


        return HttpResponseRedirect('/sepeda')
    else:
        messages.error(request, "failed")
        return HttpResponseRedirect('/sepeda/updatesepeda')

@csrf_exempt
def detailupdate(request):
    if(request.method=="POST"):
        response={}
        sepeda= request.POST['id']
        c = connection.cursor()
        c.execute('set search_path to bike_station,public')
        c.execute("select * from sepeda where nomor='"+sepeda+"';")
        stasiun = c.fetchone()

        c.execute("select s.nama from stasiun as s, sepeda as a where a.nomor ='"+sepeda+"' and a.id_stasiun = s.id_stasiun;")
        nama_stasiun = c.fetchone()

        c.execute("select p.nama from person as p, anggota as a, sepeda as n where n.nomor='"+sepeda+"' and a.no_kartu=n.no_kartu_penyumbang and p.ktp=a.ktp;")
        result = c.fetchone()
        nama_penyumbang = result[0]

        c.execute("select jenis from sepeda where nomor='"+sepeda+"';")
        jenis = c.fetchone()

        c.execute("select status from sepeda where nomor='"+sepeda+"';")
        status = c.fetchone()

        c.execute("select merk from sepeda where nomor='"+sepeda+"';")
        merk = c.fetchone()

        c.execute("select p.nama from person as p, anggota as a where a.ktp=p.ktp")
        penyumbang = c.fetchall()

        c.execute("select nama from stasiun")
        stasiun = c.fetchall()
        response['stasiun'] = stasiun
        response['penyumbang'] = penyumbang
        response['sepeda'] = sepeda
        response['nama_stasiun'] = nama_stasiun
        response['nama_penyumbang'] = nama_penyumbang
        response['jenis'] = jenis[0]
        response['merk'] = merk[0]
        response['status'] = status[0]

        return JsonResponse(response)

    else:
        messages.error(request, "failed")
        return HttpResponseRedirect('/sepeda/updatesepeda')

@csrf_exempt
def deletesepeda(request):
    if(request.method=="POST"):
        nomor= request.POST['id']
        c = connection.cursor()
        c.execute('set search_path to bike_sharing,public')
        c.execute("delete from sepeda where nomor='"+nomor+"';")

        return HttpResponseRedirect('/sepeda')
    else:
        messages.error(request, "failed")
        return HttpResponseRedirect('/sepeda')

sepeda/templates/createSepeda.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load static %}

{% block title %}
{% endblock title %}

{% block head %}
    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static 'material-design-iconic-font.css' %}">
    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- JS -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="js/main.js"></script>

{% endblock %}

{% block body %}

<!-- Add Sepeda form -->
<section class="add">
  <div class="container-edit">
      <div class="add-content">
        <div class="row">
          <div class="col-md-6">
            <div class="add-form">
                <h2 class="form-title1">Penambahan Sepeda</h2>
                <form action="/sepeda/postsepeda" method="POST">
                  {% csrf_token %}
                  <div class="form-group">
                      <input name="merk" type="text" class="form-control" id="inputMerkSepeda" placeholder="Merk" required>
                  </div>
                  <div class="form-group">
                      <input name="jenis" type="text" class="form-control" id="inputJenis" placeholder="Jenis" required>
                  </div>
                  <div class="form-group">
                      <select name="status" id="inputStatus" class="form-control"placeholder="Status"required>
                          <option>Tersedia</option>
                          <option>Tidak Tersedia</option>
                      </select>

                  </div>
                  <div class="form-group">
                    <select name="stasiun" id="inputStasiun" class="form-control"placeholder="Stasiun"required>
                    {% for i in stasiun %}
                          <option>{{i.0}}</option>
                    {% endfor %}
                  </select>

                  </div>
                  <div class="form-group">
                    <select name="penyumbang" id="inputPenyumbang" class="form-control"placeholder="Penyumbang" required>
                        {% for i in penyumbang %}
                          <option>{{i.0}}</option>
                        {% endfor %}
                      </select>

                  </div>
                  <div class="form-group form-button">
                      <input type="submit" name="add" id="add" class="form-submit" value="Submit"/>
                  </div>
                </form>
            </div>
          </div>
          <div class="col-md-6">
            <div class="add-image">
                <figure><img src="https://scontent.fcgk18-2.fna.fbcdn.net/v/t1.0-9/59487760_1566002416865635_6596520650792239104_n.jpg?_nc_cat=104&_nc_ht=scontent.fcgk18-2.fna&oh=14ff139985fcd569ad583af921d082c2&oe=5D5F5346"></figure>
            </div>
          </div>
        </div>
      </div>
    </div>
</section>

{% endblock %}

sepeda/templates/daftar_sepeda.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load static %}

{% block title %}
{% endblock title %}

{% block head %}

  <link rel="stylesheet" href="{% static 'css/style1.css' %}">
  <link rel="stylesheet" href="{% static 'material-design-iconic-font.css' %}">

<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>

<link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
<script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
{% endblock %}

{% block body %}

<!-- Add Sepeda list -->

<!-- <div class="cd-popup" role="alert">
    <div class="cd-popup-container">
          <p>Are you sure you want to delete this element?</p>
          <ul class="cd-buttons">
              <li onclick="yesFunction()"><a href="#0">Yes</a></li>
              <li onclick="cancelFunction()"><a href="#0">No</a></li>
          </ul>
    </div> <!-- cd-popup-container -->
<!-- </div> --> 

<div class="container-daftar">
    <div class="add-content">
    	<div class="row">
            <h2 class="form-title1">Daftar Sepeda</h2>

            </div>
            {% if request.session.role == "petugas" %}
            <div class="table-responsive">
            <table id="mytable" class="table table-bordred table-striped">

               <thead>
                  <th style="text-align: center;">Nomor</th>
                  <th style="text-align: center;">Merk</th>
                  <th style="text-align: center;">Jenis</th>
                  <th style="text-align: center;">Status</th>
                  <th style="text-align: center;">Stasiun</th>
                  <th style="text-align: center;">Penyumbang</th>
                  <th style="text-align: center;">Action</th>
               </thead>
              <tbody>
               {% for i in sepeda %}
                    <tr>
                    <td>{{i.2}}</td>
                    <td>{{i.3}}</td>
                    <td>{{i.4}}</td>
                    <td>{{i.5}}</td>
                    <td>{{i.0}}</td>
                    <td>{{i.1}}</td>
                    <td><a data-placement="top" data-toggle="tooltip" href="{% url 'sepeda:updatesepeda' %}" title="Update"><button class="btn btn-primary btn-xs" data-title="Edit" data-toggle="modal" data-target="#edit" >Update</button></a>
                        <a data-placement="top" data-toggle="tooltip" title="Delete"><a href="{% url 'sepeda:deletesepeda' %}" class="btn btn-danger btn-xs" data-title="Edit" data-toggle="modal" data-target="#edit"  onclick="return confirm('Are you sure you want to delete this item?');">Delete</a></td>
                {% endfor %}
                </tbody>

            </table>
          {% elif request.session.role == "anggota" %}
          <table id="mytable" class="table table-bordred table-striped">

             <thead>
                <th style="text-align: center;">Nomor</th>
                <th style="text-align: center;">Merk</th>
                <th style="text-align: center;">Jenis</th>
                <th style="text-align: center;">Status/th>
                <th style="text-align: center;">Stasiun</th>
                <th style="text-align: center;">Penyumbang</th>
                <th style="text-align: center;">Action</th>
             </thead>
            <tbody>
             {% for i in sepeda %}
                  <tr>
                  <td>{{i.2}}</td>
                  <td>{{i.3}}</td>
                  <td>{{i.4}}</td>
                  <td>{{i.5}}</td>
                  <td>{{i.0}}</td>
                  <td>{{i.1}}</td>
                  <td><a data-placement="top" data-toggle="tooltip" title="Pinjam"><button class="btn btn-primary btn-xs {{i.5}}" onclick="pinjam(this.id)" id= "{{i.2}}"" >Pinjam</button></a></td>
                  </tr>
              </tbody>
              {% endfor %}
          </table>
          {% endif %}
          </div>
    	</div>
  </div>
</div>

<script src="{% static '/js/main.js' %}"></script>

{% endblock %}

sepeda/templates/updateSepeda.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load static %}

{% block title %}
{% endblock title %}

{% block head %}
    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static 'material-design-iconic-font.css' %}">
    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- JS -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="js/main.js"></script>


{% endblock %}

{% block body %}

<section class="update">
    <div class="container-edit">
        <div class="update-content">
          <div class="row">
            <div class="col-md-6">
              <div class="update-image">
                  <figure><img src="https://scontent.fcgk18-1.fna.fbcdn.net/v/t1.0-9/59710129_1566002423532301_945452520963047424_n.jpg?_nc_cat=105&_nc_ht=scontent.fcgk18-1.fna&oh=fc4b9a06ffeb557441c11e096a563595&oe=5D7028CF"></figure>
              </div>
            </div>
            <div class="col-md-6">
              <div class="update-form">
                  <h2 class="form-title">Update Sepeda</h2>
                  <form action="/sepeda/postsepeda" method="POST">
                    <div class="form-group">
                        <label for="name"><i class="name"></i></label>
                        <input type="text" name="name" id="name" placeholder="Merk" required />
                    </div>
                    <div class="form-group">
                        <label for="name"><i class="name"></i></label>
                        <input type="text" name="name" id="name" placeholder="Jenis" required />
                    </div>
                    <div class="form-group">
                        <label for="name"><i class="name"></i></label>
                        <input type="text" name="name" id="name" placeholder="Status" required />
                    </div>
                    <div class="form-group">
                        <label for="name"><i class="name"></i></label>
                        <input type="text" name="name" id="name" placeholder="Stasiun" required />
                    </div>
                    <div class="form-group">
                        <label for="name"><i class="name"></i></label>
                        <input type="text" name="name" id="name" placeholder="Penyumbang" />
                    </div>
                    <div class="form-group form-button">
                        <input type="submit" name="update" id="update" class="form-submit" value="Update"/>
                    </div>
                  </form>
              </div>
            </div>
          </div>
        </div>
    </div>
</section>
{% endblock %}